# Docker Compose file for Guitar Song Simplifier API

services:
  guitar-song-simplifier:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for development (comment out for production)
      - ./src:/app/src:ro
      # Mount a volume for temporary audio files if needed
      - audio_cache:/tmp/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audio_cache: 